Features/prot 50 pull data for medication notes and vitals from firestore
nickdlc/Protego pull request #35
Opened 2022-03-30 18:49 UTC by chelseaL01

2022-03-30 20:59 UTC, kareem-ib requested changes
`randomApprovedDoctors()` may add 0 doctors to the patient in which case creating the random medication for the patient in `ProtegoHomeController.java:460` will call a range of 0 to -1 which will throw an error.

2022-03-31 01:05 UTC, kareem-ib approved these changes

2022-03-31 01:47 UTC, nickdlc approved these changes

2022-03-31 01:55 UTC, Gkimatov approved these changes

2022-03-31 03:01 UTC, merged