Features/prot 66 connect onboarding fields to firestore
nickdlc/Protego pull request #54
Opened 2022-05-05 19:18 UTC by chelseaL01

2022-05-05 20:07 UTC, nickdlc requested changes
Addressed a couple minor UI issues. The comment about the final, static arrays of size 1 is more an observation than a request to change things.

Also, I didn't address this in a file directly, but the Onboarding page should denote which fields are required. I think it's everything except medical history, but we should at least denote that so the "Please complete required fields" message is clearer.

2022-05-05 20:07 UTC, nickdlc commented on client/app/src/main/res/layout/activity_patient_general_info.xml
> +                        <TextView
Long addresses are cut off from the general info display (e.g. "401 W 130th St, New York, NY 10027" displays as "401 W 130th St, New").

2022-05-05 20:07 UTC, nickdlc commented on client/app/src/main/java/com/example/protego/PatientOnboardingActivity.java
> +                String Height = Height_Feet + "'" + Height_Inches + " feet";
Height is displayed incorrectly (e.g. `5'4"` displays as `5'4 feet`). Alternatives could be `x feet, y inches` or `x'y"`.

2022-05-05 20:07 UTC, nickdlc commented on client/app/src/main/java/com/example/protego/PatientGeneralInfoActivity.java
> +    public final static String[] phoneData = new String[1];
I think it should be possible to avoid instances of having to use final, static arrays of size 1, but this isn't the most important change given the time remaining (There should be some instances where this is avoided somewhere, but I don't recall off the top of my head).

2022-05-05 21:47 UTC, chelseaL01 commented on client/app/src/main/res/layout/activity_patient_general_info.xml
> +                        <TextView
I updated the general information and emergency contact information textviews to show long texts.

2022-05-05 21:48 UTC, chelseaL01 commented on client/app/src/main/java/com/example/protego/PatientOnboardingActivity.java
> +                String Height = Height_Feet + "'" + Height_Inches + " feet";
A patient's height is now saved to firestore with the units "feet" and "inches" and is shown on the general information page.

2022-05-05 21:50 UTC, chelseaL01 commented on client/app/src/main/res/layout/activity_patient_general_info.xml
> +                        <TextView
I updated the onboarding design to show required onboarding fields with an * before the question and with the phrase "(Required)" after the question. We can highlight the required fields in a different way if you think there is better way to show it ?

2022-05-05 22:21 UTC, nickdlc commented on client/app/src/main/res/layout/activity_patient_general_info.xml
> +                        <TextView
I think * is just enough and we can maybe just say "* denotes required field" at the top of the page.

2022-05-05 22:23 UTC, chelseaL01 commented on client/app/src/main/java/com/example/protego/PatientGeneralInfoActivity.java
> +    public final static String[] phoneData = new String[1];
I made updates to the PatientDashboard and PatientGeneralInfo Activities. I pull the onboarding fields from the dashboard to display the information in time when the user navigates to PatientGeneralInfo. The variables are now static strings on the dashboard code. Initially I pulled the firestore fields on the general information activity but the UI components would not update in time. I updated this code too to strings if we want to use the code later on

2022-05-06 00:26 UTC, nickdlc approved these changes

2022-05-06 00:26 UTC, merged